# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
remote_theme: "mmistakes/minimal-mistakes"

# Site Settings
locale                   : "en-US"
title                    : "Mikey Bronowski - Blog"
url                      : "https://mikeybronowski.com"
title_separator          : "-"
name                     : "Mikey Bronowski"
description              : "Mikey Bronowski blogs about data"
baseurl                  : 
gh_repo                  :
teaser                   : 
# breadcrumbs            : false # true, false (default)
reading_time             : false
words_per_minute         : 200
comments:
  #  provider               : # false (default), "disqus", "facebook", "google-plus", custom"
  provider: 
  disqus:
    shortname: 
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts: 5
    colorscheme: # "light" (default), "dark"

# Multilanguage
lang: en
# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
twitter:
  username: MikeyBronowski
facebook:
  username:
  app_id:
  publisher:
og_image: "Untitled.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/MikeyBronowski"
    - "https://www.linkedin.com/in/MikeyBronowski"

# Analytics
analytics:
  #  provider               : false # false (default), "google", "google-universal", "custom"
  provider: "google-universal"
  google:
    tracking_id: 

# Google AdSense
google_ad_client:
google_ad_slot:

# Site Author
author:
  name: "Mikey Bronowski"
  avatar: 
  bio: 
  location: "UK"
  email: mikeybronowski@gmail.com
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "MikeyBronowski"
  gitlab: 
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin: MikeyBronowski
  pinterest:
  soundcloud:
  stackoverflow: 
  steam:
  tumblr:
  twitter: "MikeyBronowski"
  vine:
  weibo:
  xing:
  youtube:

# Reading Files
include:
  - .htaccess
  - _pages
  - _books
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
categories:
  # type: jekyll-archives
  type: liquid
  path: /categories/
tags:
  # type: jekyll-archives
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
# enabled:
# - categories
# - tags
# layouts:
# category: archive-taxonomy
# tag: archive-taxonomy
# permalinks:
# category: /categories/:name/
# tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  books:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _books
  - scope:
      path: ""
      type: books
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
